[package]
name = "clist-mempool-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
linked-hash-map = "0.5"
sha2 = "0.10"

[build-dependencies]
cbindgen = "0.20.0"
